### ISSUE TITLE
import save issue 

### ISSUE THREAD

**Issue by Orionsilver** [trigger-death/TriggersPC#4]
and this is the result 

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PokemonManager.PokemonStructures.GBAPokePC.Load(Byte[] data)
   at PokemonManager.Game.FileStructure.Gen3.GBA.BlockDataCollection..ctor(GBAGameSave gameSave, Byte[] data)
   at PokemonManager.Game.FileStructure.Gen3.GBA.GBASaveData..ctor(GBAGameSave gameSave, Byte[] data)
   at PokemonManager.Game.FileStructure.Gen3.GBA.GBAGameSave..ctor(String filePath, GameTypes gameType, Boolean japanese)
   at PokemonManager.PokeManager.LoadGameSave(String filePath, GameTypes gameType, Boolean japanese)
   at PokemonManager.PokeManager.MakeNewGameSaveFileInfo(String filePath, GameTypes gameType, Boolean japanese)
   at PokemonManager.Windows.SaveManager.OnAddSaveClicked(Object sender, RoutedEventArgs e)

**Comment by trigger-death** [comment]
**1)** Could you send me your save file? If you don't want it made public like others I've known then I can give you a contact method.

**2)** Has this save file been saved over with Trigger's PC in the past? Have any exception windows opened up in the past?

**Comment by otr87** [comment]
I recently just discovered this tool that would be able to help in my advanced game of pokemon ruby and unfortunately it appeared in this error and I would like to know if there is already a solution
