### ISSUE TITLE
Cannot import native .sav file for Ruby

### ISSUE THREAD

**Issue by brick90** [trigger-death/TriggersPC#8]
i have gotten a lot of use out of your program, but when i try to import my Ruby .sav file, it gives an Unhandled Exception error. here are the details from the program.

System.NullReferenceException: Object reference not set to an instance of an object.
   at PokemonManager.Game.FileStructure.Gen3.GBA.BlockDataCollection..ctor(GBAGameSave gameSave, Byte[] data)
   at PokemonManager.Game.FileStructure.Gen3.GBA.GBASaveData..ctor(GBAGameSave gameSave, Byte[] data)
   at PokemonManager.Game.FileStructure.Gen3.GBA.GBAGameSave..ctor(String filePath, GameTypes gameType, Boolean japanese)
   at PokemonManager.PokeManager.LoadGameSave(String filePath, GameTypes gameType, Boolean japanese)
   at PokemonManager.PokeManager.MakeNewGameSaveFileInfo(String filePath, GameTypes gameType, Boolean japanese)
   at PokemonManager.Windows.SaveManager.OnAddSaveClicked(Object sender, RoutedEventArgs e)

**Comment by SkyVortex1080** [comment]
Very old post, but for anyone having this problem it might be a result of the .SAV's file size being off a bit. That can happen with certain emulators, like mGBA (I use it, it's great). The later versions keep some additional data at the very end of RSE save files, which is harmless, but for old programs like Trigger's PC it can cause it to give errors.

I don't know if the above error is from that specifically, but the fix I use is to open the .SAV in a hex-editor like HxD. Just scroll all the way down and delete the last line of data, then save changes. Just make sure that before you do this, make a backup copy. The result is that the save go from 129KB to 128KB, letting it open in Trigger's PC.

**Comment by SkyVortex1080** [comment]
I don't know if you found a solution already, but for anyone reading this, try this solution for now (make backups of your saves just in case):
https://github.com/trigger-segfault/TriggersPC/issues/12#issuecomment-3537115399
